/**
 * Odak: lacivert / yumuşak yeşil. Sarı ve parlak kırmızıdan kaçınılır
 * (yalnızca ileride “kritik süre” gibi özel durumlar için ayrıldı).
 */
export type ThemeColors = {
  bg: string;
  bgSubtle: string;
  surface: string;
  surfaceMuted: string;
  border: string;
  borderStrong: string;
  text: string;
  textSecondary: string;
  textMuted: string;
  primary: string;
  primaryMuted: string;
  onPrimary: string;
  link: string;
  chip: string;
  chipActive: string;
  chipText: string;
  chipTextActive: string;
  segmentOff: string;
  segmentOn: string;
  segmentText: string;
  segmentTextOn: string;
  success: string;
  successBg: string;
  successBorder: string;
  admin: string;
  onAdmin: string;
  overlay: string;
  errorText: string;
  errorBg: string;
  statusIdle: string;
  statusProgress: string;
  statusDone: string;
  statusReview: string;
  celebrateBg: string;
  celebrateBorder: string;
  celebrateText: string;
  removeAsideBg: string;
  removeAsideBorder: string;
  removeAsideText: string;
  dangerText: string;
  sectionAccent: string;
  streakBg: string;
  streakBorder: string;
  streakText: string;
  streakTitle: string;
  barTrack: string;
  barFill: string;
  barFillWin: string;
  statAccent: string;
  statAccent2: string;
  netPositive: string;
  difficultyOn: string;
  tabInactive: string;
  tabBg: string;
  tabBorder: string;
  headerBg: string;
  groupHeaderBg: string;
  groupHeaderText: string;
  modalSurface: string;
  badgeTyt: string;
  badgeAyt: string;
  badgeYdt: string;
  badgeBrans: string;
  badgeText: string;
  inputBg: string;
  inputBorder: string;
  keyboardAppearance: 'light' | 'dark';
};

export const lightColors: ThemeColors = {
  bg: '#e8edf4',
  bgSubtle: '#eef2f7',
  surface: '#ffffff',
  surfaceMuted: '#f4f7fb',
  border: '#d3dde8',
  borderStrong: '#c5d0dc',
  text: '#0f172a',
  textSecondary: '#475569',
  textMuted: '#64748b',
  primary: '#1e3a5f',
  primaryMuted: '#2c5282',
  onPrimary: '#f8fafc',
  link: '#2563eb',
  chip: '#e8eef5',
  chipActive: '#d4e3f4',
  chipText: '#334155',
  chipTextActive: '#1e3a5f',
  segmentOff: '#e8eef5',
  segmentOn: '#1e3a5f',
  segmentText: '#475569',
  segmentTextOn: '#f1f5f9',
  success: '#2d6a4f',
  successBg: '#e8f5ef',
  successBorder: '#a3d4b8',
  admin: '#2f6f5e',
  onAdmin: '#f8fafc',
  overlay: 'rgba(15, 23, 42, 0.5)',
  errorText: '#6b3d4a',
  errorBg: '#f7f0f2',
  statusIdle: '#64748b',
  statusProgress: '#0d9488',
  statusDone: '#2d6a4f',
  statusReview: '#4c63b6',
  celebrateBg: '#e8f5ef',
  celebrateBorder: '#a3d4b8',
  celebrateText: '#1b4332',
  removeAsideBg: '#f0f4f8',
  removeAsideBorder: '#dce4ee',
  removeAsideText: '#5c4a50',
  dangerText: '#6b3d4a',
  sectionAccent: '#1e3a5f',
  streakBg: '#e4ebf5',
  streakBorder: '#b8c9e0',
  streakText: '#1e3a5f',
  streakTitle: '#1e3a5f',
  barTrack: '#e2e8f0',
  barFill: '#2c5282',
  barFillWin: '#3d8b6a',
  statAccent: '#2c5282',
  statAccent2: '#4c63b6',
  netPositive: '#2d6a4f',
  difficultyOn: '#0d9488',
  tabInactive: '#64748b',
  tabBg: '#ffffff',
  tabBorder: '#d3dde8',
  headerBg: '#e8edf4',
  groupHeaderBg: '#e8eef5',
  groupHeaderText: '#475569',
  modalSurface: '#ffffff',
  badgeTyt: '#d4e3f4',
  badgeAyt: '#e4e1f0',
  badgeYdt: '#d8f0e4',
  badgeBrans: '#dde3f5',
  badgeText: '#334155',
  inputBg: '#ffffff',
  inputBorder: '#c5d0dc',
  keyboardAppearance: 'light',
};

export const darkColors: ThemeColors = {
  bg: '#0f1419',
  bgSubtle: '#131a22',
  surface: '#1a2330',
  surfaceMuted: '#151d28',
  border: '#2a3545',
  borderStrong: '#354252',
  text: '#e8eef4',
  textSecondary: '#a8b8cc',
  textMuted: '#8b9cb3',
  primary: '#5b8cc9',
  primaryMuted: '#7aa8d9',
  onPrimary: '#0a0e14',
  link: '#7eb8ff',
  chip: '#243041',
  chipActive: '#2d3f56',
  chipText: '#c5d4e5',
  chipTextActive: '#d4e6fa',
  segmentOff: '#243041',
  segmentOn: '#3d5a80',
  segmentText: '#a8b8cc',
  segmentTextOn: '#f1f5f9',
  success: '#6bbf8f',
  successBg: '#15261e',
  successBorder: '#2d5a45',
  admin: '#5a9e7a',
  onAdmin: '#0a0e14',
  overlay: 'rgba(0, 0, 0, 0.72)',
  errorText: '#d4a5b0',
  errorBg: '#261a1f',
  statusIdle: '#8b9cb3',
  statusProgress: '#2dd4bf',
  statusDone: '#6bbf8f',
  statusReview: '#93b4fc',
  celebrateBg: '#15261e',
  celebrateBorder: '#2d5a45',
  celebrateText: '#86d9a8',
  removeAsideBg: '#241f22',
  removeAsideBorder: '#3d3438',
  removeAsideText: '#d4a5b0',
  dangerText: '#d4a5b0',
  sectionAccent: '#8eb4e8',
  streakBg: '#1a2740',
  streakBorder: '#2d4a6f',
  streakText: '#a8c8f0',
  streakTitle: '#c5daf7',
  barTrack: '#243041',
  barFill: '#5b8cc9',
  barFillWin: '#4a9d6f',
  statAccent: '#7eb8ff',
  statAccent2: '#a5b4fc',
  netPositive: '#6bbf8f',
  difficultyOn: '#2dd4bf',
  tabInactive: '#8b9cb3',
  tabBg: '#1a2330',
  tabBorder: '#2a3545',
  headerBg: '#131a22',
  groupHeaderBg: '#243041',
  groupHeaderText: '#a8b8cc',
  modalSurface: '#1a2330',
  badgeTyt: '#2a3f56',
  badgeAyt: '#322a45',
  badgeYdt: '#1a3328',
  badgeBrans: '#2a3145',
  badgeText: '#c5d4e5',
  inputBg: '#1a2330',
  inputBorder: '#354252',
  keyboardAppearance: 'dark',
};
